#!/bin/bash
    

function banner () {
    echo
    echo "========================================================"
    echo $1
    echo "========================================================"
    echo
}

function request () {
    echo
    echo "===================== TAKE ACTION! ====================="
    echo $1
    echo "========================================================"
    echo
}

# Get latest version
if ! [ "$1." = "up-to-date." ]; then
    wget https://github.com/NVSL/gadgetron-vm-util/raw/master/checkout_gadgetron;
    chmod u+x checkout_gadgetron ;
    exec ./checkout_gadgetron up-to-date
fi

# get sudo permision early.
sudo true

if ! [ -e "./Gadgetron" -a -e ~/.ssh/id_rsa.pub ]; then
    request Enter your NVSL lab username:
    read user
fi
    
    
if ! [ -e ~/.ssh/id_rsa.pub ]; then 
    request "Generating public key.  Please accept all the defaults"
    ssh-keygen
    eval `ssh-agent`
    ssh-add
    request "Provide NVSL password to transfer pub key to svn repo"
    cat .ssh/id_rsa.pub | ssh $user@bbfs-01.calit2.net "cat >> .ssh/authorized_keys"

    request  'Visit https://github.com/settings/ssh, and add this key by copying and pasting it into the space provided.  Give it a meaningful name, like "Gadgetron Development Key"'
    cat .ssh/id_rsa.pub

    request "PRESS RETURN WHEN YOU HAVE DONE SO. (waiting...)"
    read junk
    
fi

eval `ssh-agent`
ssh-add

banner "Checking out and building gadgetron:"

if ! [ -d "Gadgetron" ]; then
    mkdir Gadgetron
    (cd Gadgetron
    svn checkout -N svn+ssh://$user@bbfs-01.calit2.net/grw/Gordon/svn/trunk .
    ./initial_setup gadgets
    source setup_gadgets)
fi

kill $(ps aux | grep dev_appserver.py | grep -v grep | perl -ne 's/\s+/ /g; @a = split(" "); print $a[1]')

cd Gadgetron
./update_gadgets

banner Done!

request Type 'make run' to start jet.


#sleep 1;
#nohup google-chrome http://localhost:8080 &
