#!/bin/bash
    

if ! [ -e "./Gadgetron" -a -e ~/.ssh/id_rsa.pub ]; then
    echo Enter your NVSL lab username:
    read user
fi
    
    
if ! [ -e ~/.ssh/id_rsa.pub ]; then 
    echo "Generating public key (accept all the defaults):"
    ssh-keygen
    eval `ssh-agent`
    ssh-add
    echo "Provide NVSL password to transfer pub key to svn repo"
    cat .ssh/id_rsa.pub | ssh $user@bbfs-01.calit2.net "cat >> .ssh/authorized_keys"

    echo -ne 'Visit https://github.com/settings/ssh, and add this key by copying and pasting it into the space provided.  Give it a meaningful name, like "Gadgetron Development Key":\n\n'
    cat .ssh/id_rsa.pub

    echo -ne "\n\n"
    echo "PRESS RETURN WHEN YOU HAVE DONE SO. (waiting...)"
    read junk
    
fi

eval `ssh-agent`
ssh-add


echo "Checking out and building gadgetron (accept all the default, if asked):"


if ! [ -d "Gadgetron" ]; then
    mkdir Gadgetron
    (cd Gadgetron
    svn checkout -N svn+ssh://$user@bbfs-01.calit2.net/grw/Gordon/svn/trunk .
    ./initial_setup gadgets
    source setup_gadgets)
fi
cd Gadgetron
./update_gadgets
cd Gadgets/Tools/jet_2/
yes y | dev_appserver.py ./ &
sleep 1;
nohup google-chrome http://localhost:8080 &

